### ISSUE TITLE
bookshelf-scopes is not working in bookshelfjs 1.5.0

### ISSUE THREAD

**Issue by amaranadh-wal** [jtwebman/bookshelf-scopes#3]
**error: TypeError: Cannot read property 'push' of undefined**
`[0]     at /Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf-scopes/src/scopes.js:16:38
[0]     at Array.forEach (<anonymous>)
[0]     at Builder.<anonymous> (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf-scopes/src/scopes.js:15:6)
[0]     at Object.query (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf/lib/helpers.js:68:14)
[0]     at Child.query (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf/lib/model.js:1311:30)
[0]     at Child.Target.(anonymous function) [as newest] (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf-scopes/src/scopes.js:50:21)
[0]     at Function.Target.(anonymous function) [as newest] (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/bookshelf-scopes/src/scopes.js:60:35)
[0]     at _passport.passport.authenticate (/Users/amaranadhmeda/projects/injo/ijrv2-api/src/controllers/commentables.js:32:23)
[0]     at allFailed (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/authenticate.js:107:18)
[0]     at attempt (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/authenticate.js:180:28)
[0]     at JwtStrategy.strategy.fail (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/authenticate.js:297:9)
[0]     at JwtStrategy.authenticate (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport-jwt/lib/strategy.js:96:21)
[0]     at attempt (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/authenticate.js:361:16)
[0]     at authenticate (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/authenticate.js:362:7)
[0]     at list (/Users/amaranadhmeda/projects/injo/ijrv2-api/src/controllers/commentables.js:9:3)
[0]     at Layer.handle [as handle_request] (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/route.js:112:3)
[0]     at Layer.handle [as handle_request] (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/layer.js:95:5)
[0]     at /Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:281:22
[0]     at Function.process_params (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:275:10)
[0]     at initialize (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/passport/lib/middleware/initialize.js:53:5)
[0]     at Layer.handle [as handle_request] (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/amaranadhmeda/projects/injo/ijrv2-api/node_modules/express/lib/router/index.js:275:10) id=5fad3239-9daf-45e3-b241-dcd03d85b00d
[0] TypeError: Cannot read property 'push' of undefined`

**Comment by brunocascio** [comment]
@amaranadh-wal do you solve this?

**Comment by jtwebman** [comment]
I haven't used the library in a while but let me take a look tonight to see if I can't fix this.

**Comment by jtwebman** [comment]
Ok so I updated to the latest code and all my tests are still passing.  @brunocascio @amaranadh-wal I am going to need to see some code that recreates the issue.

**Comment by lholden** [comment]
For the record, this seems to happen when calling `this.addScope()` from `initialize`

Instead of calling that function from initialize you can instead call:
```
    this.constructor.__super__.initialize.apply(this, arguments);
```
It will add the scopes as expected.

I think the main issue here is just that the documentation needs updating :)
